---
# DC2 fabric vars

underlay_routing_protocol: EBGP
overlay_routing_protocol: EBGP

p2p_uplinks_mtu: 9214

evpn_import_pruning: true

bgp_peer_groups:
  ipv4_underlay_peers:
    name: IPV4-UNDERLAY-PEERS
    password: X/OrLne2MxtUwJOXyoEcEw==
  mlag_ipv4_underlay_peer:
    name: MLAG-IPV4-UNDERLAY-PEER
    password: 96Yo/G3L+2RCoAD4Cy/2Ew==
  evpn_overlay_peers:
    name: EVPN-OVERLAY-LOCAL-PEERS
    password: HwsUtvRBaFIOmUOBhrtIfQ==
  evpn_overlay_core:
    name: EVPN-OVERLAY-REMOTE-PEERS
    password: N5U6i+3vPyc1DrMdKl+ljQ==

##################################################
# DC2 Spines                                     #
##################################################
spine:
  defaults:
    platform: ceos
    bgp_as: 65100
    loopback_ipv4_pool: 10.1.0.0/24
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'neighbor default send-community'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    - name: s2-spine1
      id: 110
      mgmt_ip: 192.168.0.20/24
    - name: s2-spine2
      id: 112
      mgmt_ip: 192.168.0.21/24

##################################################
# DC2 Leaf Pairs                                 #
##################################################
l3leaf:
  defaults:
    platform: ceos
    loopback_ipv4_pool: 10.1.0.0/24
    vtep_loopback_ipv4_pool: 10.1.1.0/24
    uplink_interfaces: [Ethernet2, Ethernet3]
    uplink_switches: [s2-spine1, s2-spine2]
    uplink_ipv4_pool: 10.255.0.0/22
    mlag_interfaces: [Ethernet1, Ethernet6]
    mlag_peer_ipv4_pool: 192.0.0.0/24
    mlag_peer_l3_ipv4_pool: 192.1.1.0/24
    mlag_port_channel_id: 1000
    virtual_router_mac_address: 00:1c:73:00:00:01
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'neighbor default send-community'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    spanning_tree_mode: rapid-pvst
    spanning_tree_priority: 0
    structured_config:
      spanning_tree:
        edge_port:
          bpduguard_default: true
  node_groups:
    ####################################################
    # DC2 Border Leafs                                 #
    ####################################################
    # - group: BrdrLeafs
    #   platform: ceos
    #   structured_config:
    #     router_bgp:
    #       address_family_ipv4:
    #         networks:
    #           10.231.0.2/32:
    #           10.231.0.4/32:
    #           10.231.1.2/32:
    #   filter:
    #     tenants: [ATD_DC]
    #     tags: ['DC']
    #   bgp_as: 65199
    #   evpn_gateway:
    #     evpn_l2:
    #       enabled: true
    #     remote_peers:
    #     - hostname: s1-brdr1
    #       ip_address: 10.1.0.2
    #       bgp_as: 65099
    #     - hostname: s1-brdr2
    #       ip_address: 10.1.0.4
    #       bgp_as: 65099
    #   nodes:
    #     - name: s2-brdr1
    #       id: 102
    #       mgmt_ip: 192.168.0.200/24
    #       uplink_switch_interfaces: [Ethernet7, Ethernet7]
    #       uplink_interfaces: [Ethernet2, Ethernet3]
    #       mlag_interfaces: [Ethernet1, Ethernet6]
    #       structured_config:
    #         router_bgp:
    #           neighbors:
    #             172.16.255.129:
    #               remote_as: 65502
    #               description: s2-core1 VRF Default
    #               peer_group: IPV4-UNDERLAY-PEERS
    #             172.16.255.131:
    #               remote_as: 65502
    #               description: s2-core2 VRF Default
    #               peer_group: IPV4-UNDERLAY-PEERS
    #     - name: s2-brdr2
    #       id: 104
    #       mgmt_ip: 192.168.0.201/24
    #       uplink_switch_interfaces: [Ethernet8, Ethernet8]
    #       uplink_interfaces: [Ethernet2, Ethernet3]
    #       mlag_interfaces: [Ethernet1, Ethernet6]
    #       structured_config:
    #         router_bgp:
    #           neighbors:
    #             172.16.255.133:
    #               remote_as: 65502
    #               description: s2-core1 VRF Default
    #               peer_group: IPV4-UNDERLAY-PEERS
    #             172.16.255.135:
    #               remote_as: 65502
    #               description: s2-core2 VRF Default
    #               peer_group: IPV4-UNDERLAY-PEERS

    ####################################################
    # DC2 Leaf Pair 1                                  #
    ####################################################
    - group: LeafPair1
      filter:
        tenants: [ATD_DC]
        tags: ['DC']
      bgp_as: 65101
      nodes:
        - name: s2-leaf1
          id: 114
          mgmt_ip: 192.168.0.22/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
        - name: s2-leaf2
          id: 116
          mgmt_ip: 192.168.0.23/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]

    ####################################################
    # DC2 Leaf Pair 2                                  #
    ####################################################
    - group: LeafPair2
      filter:
        tenants: [ATD_DC]
        tags: ['DC']
      bgp_as: 65102
      nodes:
        - name: s2-leaf3
          id: 115
          mgmt_ip: 192.168.0.24/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
        - name: s2-leaf4
          id: 117
          mgmt_ip: 192.168.0.25/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5]

####################################################
# External Fabric PtP L3 Conncectivity             #
####################################################
core_interfaces:
  p2p_links:
    ############################################################
    # s2-brdr1 to s2-cores UNDERLAY (Default VRF) Peerings     #
    ############################################################
    - ip: [ 172.16.255.128/31, 172.16.255.129/31 ]
      nodes: [ s2-brdr1, s2-core1 ]
      interfaces: [ Ethernet4, Ethernet2 ]
      include_in_underlay_protocol: false
      mtu: 9214
    - ip: [ 172.16.255.130/31, 172.16.255.131/31 ]
      nodes: [ s2-brdr1, s2-core2 ]
      interfaces: [ Ethernet5, Ethernet2 ]
      include_in_underlay_protocol: false
      mtu: 9214
    ############################################################
    # s2-brdr2 to s2-cores UNDERLAY (Default VRF) Peerings     #
    ############################################################
    - ip: [ 172.16.255.132/31, 172.16.255.133/31 ]
      nodes: [ s2-brdr2, s2-core1 ]
      interfaces: [ Ethernet4, Ethernet3 ]
      include_in_underlay_protocol: false
      mtu: 9214
    - ip: [  172.16.255.134/31, 172.16.255.135/31 ]
      nodes: [ s2-brdr2, s2-core2 ]
      interfaces: [ Ethernet5, Ethernet3 ]
      include_in_underlay_protocol: false
      mtu: 9214