---
- name: Deploy DC1 Configurations via EAPI
  hosts: dc1_fabric
  tasks:

    - name: load configuration from file
      arista.eos.eos_config:
        src: ../sites/dc1/intended/configs/{{inventory_hostname}}.cfg

- name: validate states on EOS devices
  hosts: dc1_fabric
  connection: httpapi
  gather_facts: false
  collections:
    - arista.avd

  tasks:

    - name: validate states on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
